<a href="https://colab.research.google.com/github/MNKCrypto/dataanalysis-python/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing necessary packages
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [2]:
#Introduction to Tensors

### Creating Tensors

# Scalar:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Dimension of the scalar
scalar.ndim

0

In [4]:
# Get the tensor back as Python int
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([5,7])
vector

tensor([5, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]
                         ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0][0]

tensor([1, 2, 3])

In [16]:
## Random tensors
# Create a random tensor fo size (3,4)
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.0641, 0.5506, 0.2891, 0.2449],
        [0.8707, 0.4302, 0.7039, 0.6825],
        [0.8697, 0.1360, 0.9159, 0.2663]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image sensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color chanels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim


(torch.Size([224, 224, 3]), 3)

In [19]:
#Zeros and Ones

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [22]:
#Creating a range of tensors and tensors-like
# Using torch.range()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
#Float_32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor = torch.tensor([3.0,6.0],
                               dtype=None, #What datatype is the tensor (float32,float64, int32 etc..)
                               device=None,
                               requires_grad=False)

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6.], dtype=torch.float16)

In [28]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4945, 0.5527, 0.5110, 0.9325],
        [0.3019, 0.2160, 0.6320, 0.6188],
        [0.3124, 0.9050, 0.4631, 0.5188]])

In [29]:
print(some_tensor)
print(f"Data type of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Size of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")


tensor([[0.4945, 0.5527, 0.5110, 0.9325],
        [0.3019, 0.2160, 0.6320, 0.6188],
        [0.3124, 0.9050, 0.4631, 0.5188]])
Data type of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Size of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)
Tensor operations include:

   -> Addition

   -> Subtraction

   -> Multiplication(element-wise)

   -> Divison
   
   -> Matrix multiplication

In [30]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [31]:
#Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [32]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [33]:
# Pytorch in-built functions
print(torch.mul(tensor, 10))

print(torch.add(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])


In [34]:
# Matrix multiplication - Used extensively in neural networks

#Element-wise multiplication

print(tensor, '*',tensor)
print(f'Equals: {tensor*tensor}')

#Matrix multiplication

print(torch.matmul(tensor,tensor))

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
tensor(14)


In [35]:
%%time
ans = 0
for i in range(len(tensor)):
  ans += tensor[i]*tensor[i]

print(ans)

tensor(14)
CPU times: user 1.27 ms, sys: 48 µs, total: 1.32 ms
Wall time: 1.43 ms


In [36]:

%%time
print(torch.matmul(tensor,tensor))

tensor(14)
CPU times: user 586 µs, sys: 0 ns, total: 586 µs
Wall time: 591 µs


## One of the most common errors encountered in deep learning - Shape Error in matrix multiplication
## There are two main rules that performing matrix multiplication needs to satisfy:
  1. The **inner dimensions** must match

* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work

2. The resulting matrix has the shape of the ** outer dimension**:
*  `(2,3) @ (3,2)`  -> `(2,2)`
*  `(3,2) @ (2,10)`  -> `(3,10)`
















In [37]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                          [9,12]])
print(tensor_A.shape,tensor_B.shape)
torch.matmul(tensor_A,tensor_B) ## This will not work as the inner dimensions are not working

torch.Size([3, 2]) torch.Size([3, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
## To fix the issue above, we will take transpose of one of the tensor.

print(tensor_B)
print(tensor_B.T)
print(tensor_A.shape,tensor_B.T.shape)
result_tensor = torch.matmul(tensor_A,tensor_B.T)

print(result_tensor)
print(result_tensor.shape) #Shape will be the outer dimensions of the input two tensors

In [38]:
#Finding min max  mean and sum

x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [39]:
#Finding min

torch.min(x),x.min()

(tensor(0), tensor(0))

In [40]:
#Finding max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Finding average. mean() works only on float and complex datatypes. So you have to convert it before performing the mean operation

torch.mean(x.type(torch.float16)),x.type(torch.float16).mean()

In [41]:
#Sum
x.sum(),torch.sum(x)

(tensor(450), tensor(450))

In [42]:
#Finding the index where the min and max value is present

x.argmin(), x.argmax()

(tensor(0), tensor(9))

#Reshaping and Stacking
* Reshaping - Reshapes an input tensor to a defined shape
* View  - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stack -combine multiple tensores on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [43]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
#Reshape
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [45]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
#View - z shares same memory as the input x. If you modify z then x is also modified
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [47]:
torch.stack([x,x,x],dim=0),torch.stack((x,x,x),dim=1)

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5.],
         [2., 2., 2.],
         [3., 3., 3.],
         [4., 4., 4.],
         [5., 5., 5.],
         [6., 6., 6.],
         [7., 7., 7.],
         [8., 8., 8.],
         [9., 9., 9.]]))

In [48]:
#Squeeze - Removes all 1 dimensions from the tensore

x_reshaped.shape,x_reshaped.squeeze().shape

print(f"Original tensor - {x_reshaped} with shape - {x_reshaped.shape}")
print(f"After Squeeze - {x_reshaped.squeeze()}with shape - {x_reshaped.squeeze().shape}")
x_unsqueezed = x_reshaped.squeeze().unsqueeze(dim=1)
print(f"After UnSqueeze - {x_unsqueezed}with shape - {x_unsqueezed.shape}")

Original tensor - tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) with shape - torch.Size([1, 9])
After Squeeze - tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])with shape - torch.Size([9])
After UnSqueeze - tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])with shape - torch.Size([9, 1])


In [49]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order (returns a view)

x_original = torch.rand(224,224,3)
x_permuted = torch.permute(x_original,[2,0,1])
x_original.shape , x_permuted.shape



(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [50]:
#Index in in pytorch is same as numpy

x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [51]:
x[0,2,2] # index to return 9

tensor(9)

In [52]:
x[:,:,2] # index to return 3, 6, 9

tensor([[3, 6, 9]])

In [53]:
# Options available to convert from numpy to pytorch and vice versa

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
print(array.dtype,tensor.dtype)
print(array,tensor)

float64 torch.float64
[1. 2. 3. 4. 5. 6. 7.] tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [54]:
#change the value of the numpy array

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [55]:
#From Tensor to numpy

tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor, numpy_tensor

print(numpy_tensor.dtype,tensor.dtype)
print(numpy_tensor,tensor)

float32 torch.float32
[1. 1. 1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1., 1., 1.])


In [56]:
tensor = tensor + 1

numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

In [57]:
#Reproducibility in random

random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.7436, 0.2415, 0.3818, 0.2324],
        [0.2992, 0.7308, 0.0713, 0.3048],
        [0.6535, 0.8655, 0.4347, 0.7986]])
tensor([[0.5668, 0.7562, 0.6597, 0.6725],
        [0.3158, 0.8827, 0.7733, 0.8086],
        [0.9502, 0.9801, 0.4987, 0.1097]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [58]:
#Reproducible randomness

RANDOM_SEED = 134

torch.manual_seed(RANDOM_SEED)

random_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_D = torch.rand(3,4)

print(random_C)
print(random_D)
print(random_C == random_D)


tensor([[0.7193, 0.8094, 0.6276, 0.4930],
        [0.7029, 0.8868, 0.7661, 0.9742],
        [0.2591, 0.3724, 0.1418, 0.2210]])
tensor([[0.7193, 0.8094, 0.6276, 0.4930],
        [0.7029, 0.8868, 0.7661, 0.9742],
        [0.2591, 0.3724, 0.1418, 0.2210]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Running on GPU**

Options to run on GPU:

1.  Use Google Colab
2.  Setup your own GPU
3.  Use Cloud computing




In [59]:
# Check for GPU access with pytorch
torch.cuda.is_available()

#GPU count
torch.cuda.device_count()

0

**Creating tensors on the GPU**

In [60]:
tensor = torch.tensor([1,2,3],device='cpu')

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [62]:
#move tensor to GPU (if available)
device = 'cuda' if torch.cuda.is_available() else 'cpu'
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

In [63]:
#Moving tensor back to cpu since numpy cannot work on GPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])